version: '3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sales-management_app:latest
    container_name: sales_management_app_java
    ports:
      - 8080:8080
    depends_on:
      - mysql-java
      - jeager
      - prometheus
      - grafana
    command: ["-c", "/app/wait-for-mysql.sh mysql-java:3306 && java -jar /app/sales_management.jar"]
    entrypoint: ["/bin/sh"]

  mysql-java:
    image: mysql:8.0.22
    container_name: mysql-java
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: sales
      MYSQL_PASSWORD: sales
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sales_db

  jeager:
    image: jaegertracing/all-in-one:1.21
    container_name: jaeger
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411

  prometheus:
    image: prom/prometheus:v2.24.1
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:7.4.1
    container_name: grafana
    ports:
      - 3000:3000