global:
  scrape_interval:     15s 

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'sales-management'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      # - targets: ['192.168.86.8:8081']
      - targets: ['app:8080']